# This is a basic workflow to help you get started with Actions

name: Liquibase_NodeJS_GitHub-Hosted

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Please choose an environment'     
        required: true
        options: ['dev', 'test', 'prod']
        #default: 'dev'
      tags:
        description: 'Test scenario tags'
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  LBJobNodeJS:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: RunLiquibaseCLICommands
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell

      - run: |
          curl -L https://github.com/liquibase/liquibase/releases/download/v4.2.0/liquibase-4.2.0.zip --output liquibase-4.2.0.zip
          unzip -o -d liquibase liquibase-4.2.0.zip
          node --version
          node NodeJS/liquibase_"${{ github.event.inputs.environment }}".js
